dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: gulixciurli
    token: 5a7f239b8c59b2c4bb0629c3ce608e058c5c4399

     
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis ciaoooo
  - mvn compile sonar:sonar  -Dsonar.projectKey=gulixciurli_bookkCheck -Ppit  -Dmaven.javadoc.skip=true

  # - mvn clean -DskipTests
